// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpyhynblfrjzzxumyvsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdweWh5bmJsZnJqenp4dW15dnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODYxOTMsImV4cCI6MjA2NjQ2MjE5M30.x0GRMkOUyUVJCt0BkCTEaXES4ZIeBkSFbH3G2Swx-Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);